/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ArcGovCore {
  export type ProposalStruct = {
    id: BigNumberish;
    proposer: AddressLike;
    title: string;
    description: string;
    category: BigNumberish;
    ipfsHash: string;
    timestamp: BigNumberish;
    forVotes: BigNumberish;
    againstVotes: BigNumberish;
    abstainVotes: BigNumberish;
    isOpen: boolean;
  };

  export type ProposalStructOutput = [
    id: bigint,
    proposer: string,
    title: string,
    description: string,
    category: bigint,
    ipfsHash: string,
    timestamp: bigint,
    forVotes: bigint,
    againstVotes: bigint,
    abstainVotes: bigint,
    isOpen: boolean
  ] & {
    id: bigint;
    proposer: string;
    title: string;
    description: string;
    category: bigint;
    ipfsHash: string;
    timestamp: bigint;
    forVotes: bigint;
    againstVotes: bigint;
    abstainVotes: bigint;
    isOpen: boolean;
  };
}

export interface ArcGovCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeProposal"
      | "getAllProposals"
      | "getProposal"
      | "hasVoted"
      | "owner"
      | "proposalCount"
      | "proposals"
      | "submitProposal"
      | "transferOwnership"
      | "vote"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ProposalClosed" | "ProposalCreated" | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasVoted",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProposal",
    values: [string, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "closeProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasVoted", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export namespace ProposalClosedEvent {
  export type InputTuple = [
    id: BigNumberish,
    forVotes: BigNumberish,
    againstVotes: BigNumberish,
    abstainVotes: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    forVotes: bigint,
    againstVotes: bigint,
    abstainVotes: bigint
  ];
  export interface OutputObject {
    id: bigint;
    forVotes: bigint;
    againstVotes: bigint;
    abstainVotes: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    proposer: AddressLike,
    title: string,
    category: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    proposer: string,
    title: string,
    category: bigint
  ];
  export interface OutputObject {
    id: bigint;
    proposer: string;
    title: string;
    category: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    id: BigNumberish,
    voter: AddressLike,
    vote: BigNumberish
  ];
  export type OutputTuple = [id: bigint, voter: string, vote: bigint];
  export interface OutputObject {
    id: bigint;
    voter: string;
    vote: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ArcGovCore extends BaseContract {
  connect(runner?: ContractRunner | null): ArcGovCore;
  waitForDeployment(): Promise<this>;

  interface: ArcGovCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeProposal: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  getAllProposals: TypedContractMethod<
    [],
    [ArcGovCore.ProposalStructOutput[]],
    "view"
  >;

  getProposal: TypedContractMethod<
    [_id: BigNumberish],
    [ArcGovCore.ProposalStructOutput],
    "view"
  >;

  hasVoted: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        proposer: string;
        title: string;
        description: string;
        category: bigint;
        ipfsHash: string;
        timestamp: bigint;
        forVotes: bigint;
        againstVotes: bigint;
        abstainVotes: bigint;
        isOpen: boolean;
      }
    ],
    "view"
  >;

  submitProposal: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _category: BigNumberish,
      _ipfsHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_id: BigNumberish, _vote: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeProposal"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllProposals"
  ): TypedContractMethod<[], [ArcGovCore.ProposalStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [ArcGovCore.ProposalStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasVoted"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        proposer: string;
        title: string;
        description: string;
        category: bigint;
        ipfsHash: string;
        timestamp: bigint;
        forVotes: bigint;
        againstVotes: bigint;
        abstainVotes: bigint;
        isOpen: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProposal"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _category: BigNumberish,
      _ipfsHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_id: BigNumberish, _vote: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProposalClosed"
  ): TypedContractEvent<
    ProposalClosedEvent.InputTuple,
    ProposalClosedEvent.OutputTuple,
    ProposalClosedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "ProposalClosed(uint256,uint256,uint256,uint256)": TypedContractEvent<
      ProposalClosedEvent.InputTuple,
      ProposalClosedEvent.OutputTuple,
      ProposalClosedEvent.OutputObject
    >;
    ProposalClosed: TypedContractEvent<
      ProposalClosedEvent.InputTuple,
      ProposalClosedEvent.OutputTuple,
      ProposalClosedEvent.OutputObject
    >;

    "ProposalCreated(uint256,address,string,uint8)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "VoteCast(uint256,address,uint8)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
