/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ArcGovCore } from "./ArcGovCore";
export * as factories from "./factories";
export { ArcGovCore__factory } from "./factories/ArcGovCore__factory";
